export default {
  exclude: [
    /tabs\//,
    /modals\//,
    /components\//,
    /context\//,
    /utils\//,
    /enums/,
    // modules
    /// Assets\//,
    /ComponentTest/,
    /// Notification\//,
    /// InvoiceManagement\//,
    /// Licensing\//,
    /// Log\//,
    /// MaterialRequest\//,
    /modalsExamples\//,
    /// Network\//,
    /// OccurrenceRoutine\//,
    /pdfExamples\//,
    /// Permissions\//,
    /// Registration\//,
    /// Services\//,
    // /Schedule\//,
    /// Purchase\//,
    /// Person\//,
    // /Region\//,
    /// ServiceOrder\//,
    /// DocumentGenerator\//,
  ],
}
