// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function hasSome(value) {
  if (value == null) {
    return false;
  } else {
    return value !== undefined;
  }
}

function mapSomeHigherZero(list) {
  return Belt_Array.some(list, (function (item) {
                return item > 0;
              }));
}

export {
  hasSome ,
  mapSomeHigherZero ,
}
/* No side effect */
